version: "3"
services:
  database:
    container_name: postgres
    image: "postgres" 
    environment:
      POSTGRES_USER: test-user
      POSTGRES_PASSWORD: secretpassword1234
      POSTGRES_DB: test-db
    volumes:
      - database-data:/var/lib/postgresql/data/ 
    ports:
      - "5432:5432"
